# Generated by Django 4.1.7 on 2023-03-06 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Otd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idlpu', models.IntegerField()),
                ('lpu', models.CharField(max_length=255)),
                ('idotd', models.IntegerField()),
                ('otd_name', models.CharField(max_length=255)),
                ('short_otd', models.CharField(max_length=255)),
                ('activ', models.SmallIntegerField()),
                ('zav_otd', models.CharField(max_length=100)),
                ('msister', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Food_svod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_create', models.DateField(auto_created=True)),
                ('dt_svood', models.DateField(auto_created=True)),
                ('priznak', models.IntegerField(default=0)),
                ('vsego', models.IntegerField(default=0)),
                ('child', models.SmallIntegerField(default=0)),
                ('mam', models.SmallIntegerField(default=0)),
                ('mam_nofood', models.SmallIntegerField(default=0)),
                ('wow', models.SmallIntegerField(default=0)),
                ('zond', models.SmallIntegerField(default=0)),
                ('golod', models.SmallIntegerField(default=0)),
                ('diet_01_kis', models.SmallIntegerField(default=0)),
                ('diet_01_bul', models.SmallIntegerField(default=0)),
                ('diet_02', models.SmallIntegerField(default=0)),
                ('diet_03', models.SmallIntegerField(default=0)),
                ('diet_ovd', models.SmallIntegerField(default=0)),
                ('diet_shd', models.SmallIntegerField(default=0)),
                ('diet_child', models.SmallIntegerField(default=0)),
                ('diet_vdb', models.SmallIntegerField(default=0)),
                ('diet_vkb', models.SmallIntegerField(default=0)),
                ('diet_nkd', models.SmallIntegerField(default=0)),
                ('fio_ms', models.CharField(max_length=255)),
                ('idotd', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.otd')),
            ],
        ),
    ]
