# Generated by Django 4.1.7 on 2023-03-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otd',
            name='msister',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otd',
            name='zav_otd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
