# Generated by Django 4.1.7 on 2023-03-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_food_svod_diet_age_11_18_food_svod_diet_age_1_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_svod',
            name='diet_age_11_18',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='food_svod',
            name='diet_age_1_3',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='food_svod',
            name='diet_age_3_7',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='food_svod',
            name='diet_age_7_11',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
