# Generated by Django 4.1.7 on 2023-03-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_otd_id_alter_food_svod_dt_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_svod',
            name='diet_nbd',
            field=models.SmallIntegerField(default=0),
        ),
    ]
