# Generated by Django 4.1.7 on 2023-03-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_food_svod_fio_ms'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_svod',
            name='fio_ms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
