# Generated by Django 4.1.7 on 2023-03-08 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_food_svod_fio_ms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_svod',
            name='diet_vkb',
        ),
    ]
